version: '2.3'

services:
  cassandra:
    image: "cassandra:3.11.3"
    hostname: "cassandra"
    ports:
      - 9042:9042
    volumes:
      - "./cassandra/db-init.sh:/cassandra-init.sh"
    environment:
      JVM_OPTS: "-Xms512M -Xmx512M"
    command: "sh /cassandra-init.sh"
    mem_limit: 876M

  mongo:
    image: "mongo:4.0.4"
    hostname: "mongo"
    environment:
      MONGO_INITDB_DATABASE: application
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: mongo
    ports:
      - 37017:27017
    volumes:
      - "./mongo:/docker-entrypoint-initdb.d"
    mem_limit: 512M

  couchbase:
    image: "couchbase/server:community-5.0.1"
    hostname: "couchbase"
    ports:
      - 8091-8096:8091-8096
      - 11210-11211:11210-11211
    volumes:
      - "./couchbase/configure.sh:/configure.sh"
    command: "bash /configure.sh"
    mem_limit: 1024M

  postgres:
    image: "postgres:11.1"
    hostname: "postgres"
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - "./postgres:/docker-entrypoint-initdb.d"
    mem_limit: 512M