server:
  port: 8080
logging:
  level:
    "org.coinen.reactive.persistence": "DEBUG"
    "org.springframework.jdbc.core.JdbcTemplate": "DEBUG"
    "org.springframework.data.cassandra.core.cql.ReactiveCqlTemplate": "DEBUG"
    "org.springframework.data.mongodb.core.ReactiveMongoTemplate": "DEBUG"
    "org.springframework.data.couchbase": "DEBUG"
    "com.couchbase.client": "INFO"

# Database configurations (Postgres, Mongo, Cassandra)

spring:
  datasource:
      url: "jdbc:postgresql://localhost:5432/application"
      username: "postgres"
      password: "postgres"
      driver-class-name: "org.postgresql.Driver"
  data:
    cassandra:
      port: 9042
      keyspace-name: "reactive"
      fetch-size: 13
    mongodb:
      username: "mongo"
      password: "mongo"
      database: "application"
      host: "127.0.0.1"
      port: 37017

# External service configuration
external:
  service:
    url: "http://localhost:9090"

io:
  worker:
    size: 4

# Couchbase configuration

couchbase:
  cluster:
    host: "127.0.0.1"
    bucket: "bucket1"
    user: "Administrator"
    password: "password"
